"""Builds a plain-text, share-ready summary for extension workers / farmer
groups (WhatsApp/SMS friendly - short lines, no markdown)."""
from fastapi import APIRouter
from ..schemas import SummaryRequest

router = APIRouter(prefix="/api/summary", tags=["summary"])


@router.post("/text")
def build_summary(payload: SummaryRequest):
    r = payload.recommend
    lines = []
    header = f"BHUMISUTRA CROP ADVISORY"
    if payload.farmer_or_group_name:
        header += f" - {payload.farmer_or_group_name}"
    lines.append(header)
    lines.append(f"Location: {r.location.district}, {r.location.state}")
    lines.append(
        f"Groundwater: {r.groundwater.status}"
        + (f" ({r.groundwater.current_level_mbgl} mbgl)" if r.groundwater.current_level_mbgl else "")
    )
    lines.append(
        f"Weather: {r.weather.temperature_c}C, humidity {r.weather.humidity_pct}%, "
        f"rainfall {r.weather.rainfall_mm_per_day} mm/day"
    )
    lines.append("")
    lines.append("TOP RECOMMENDED CROPS:")
    for i, c in enumerate(r.recommendations, start=1):
        lines.append(
            f"{i}. {c.crop.title()} - Suitability {c.suitability_score}%, "
            f"Water: {c.water_demand}, GW Risk: {c.groundwater_risk}"
        )
    lines.append("")
    lines.append("Generated by Bhumisutra using real district soil, groundwater and weather data.")
    return {"text": "\n".join(lines)}